language: node_js
node_js:
- '10'

script:
- yarn run build
- ./test/remote-svf-to-gltf.sh $FORGE_MODEL_URN ./tmp/test/remote-svf-to-gltf

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
